### ISSUE TITLE
setting BROWSERID_URL to an IP address causes error

### ISSUE THREAD

**Issue by shane-tomlinson** [lloyd/myfavoritebeer.org#12]
PORT=3000 BROWSERID_URL=http://64.9.237.87:10002 node server/main.js 
Using BrowserID at: http://64.9.237.87:10002
listening on 127.0.0.1:3000
GET / 304 2ms
GET /js/less.js 304 1ms
GET /js/main.js 304 2ms
GET /js/jquery.js 304 1ms
GET /style.less 304 0ms
GET /i/browserid_logo_sm.png 304 0ms
GET /i/236037776_f8b7e0564d_o.jpg 304 1ms
GET /api/whoami 200 0ms
GET /i/sign_in_blue.png 304 1ms
GET / 304 1ms
GET /js/less.js 304 0ms
GET /js/jquery.js 304 0ms
GET /js/main.js 304 0ms
GET /style.less 304 1ms
GET /i/browserid_logo_sm.png 304 0ms
GET /i/236037776_f8b7e0564d_o.jpg 304 0ms
GET /api/whoami 200 0ms
GET /i/sign_in_blue.png 304 1ms
verifying with: 64.9.237.87:10002

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ENOTFOUND, Domain name not found
    at IOWatcher.callback (dns.js:74:15)

**Comment by shane-tomlinson** [comment]
This may not be a problem, needs further investigation - it seems to be loading old Javascript because the browserid window is loading dev.diresworb.org

**Comment by shane-tomlinson** [comment]
With cleared cache, loading correct javascript, but still getting error:

shane@Rowlf ~/development/myfavoritebeer.org $ PORT=3000 BROWSERID_URL=http://64.9.237.87:10002 node server/main.js 
Using BrowserID at: http://64.9.237.87:10002
listening on 127.0.0.1:3000
GET / 200 2ms
GET /js/less.js 200 5ms
GET /js/main.js 200 3ms
GET /i/browserid_logo_sm.png 200 5ms
GET /js/jquery.js 200 7ms
GET /style.less 200 1ms
GET /i/236037776_f8b7e0564d_o.jpg 200 34ms
GET /api/whoami 200 1ms
GET /i/sign_in_blue.png 200 1ms
verifying with: 64.9.237.87:10002

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ENOTFOUND, Domain name not found
    at IOWatcher.callback (dns.js:74:15)

**Comment by shane-tomlinson** [comment]
No longer an issue. Closing.
