### ISSUE TITLE
Selected version of express not compatible with current node.js

### ISSUE THREAD

**Issue by MichaelHackett** [lloyd/myfavoritebeer.org#50]
Preface: I'm a complete newbie wrt to node.js, et al., but I am under the impression that this project is intended to be a turnkey demo that should just work out of the box (clone). So I think that any issues that prevent this for the average user are worth considering, if this project is still relevant. Also, I'm running on Mac OS 10.7.3 (Lion).

So when I follow the README instructions, I download the current default version of node.js from nodejs.org, which is 0.6.10. I then try to run "npm install", and it fails, apparently because the version of express named in this project's package.json (2.4.6) is reporting that it is compatible only with node 4.1-4.x.

Shell log follows:

```
$ npm install
npm http GET https://registry.npmjs.org/express/2.4.6
npm http GET https://registry.npmjs.org/postprocess/0.0.2
npm http GET https://registry.npmjs.org/connect-cookie-session/0.0.2
npm http GET https://registry.npmjs.org/mongodb/0.9.6-16
npm http 200 https://registry.npmjs.org/connect-cookie-session/0.0.2
npm http GET https://registry.npmjs.org/connect-cookie-session/-/connect-cookie-session-0.0.2.tgz
npm http 200 https://registry.npmjs.org/postprocess/0.0.2
npm http GET https://registry.npmjs.org/postprocess/-/postprocess-0.0.2.tgz
npm http 200 https://registry.npmjs.org/express/2.4.6
npm http GET https://registry.npmjs.org/express/-/express-2.4.6.tgz
npm http 200 https://registry.npmjs.org/connect-cookie-session/-/connect-cookie-session-0.0.2.tgz
npm http 200 https://registry.npmjs.org/postprocess/-/postprocess-0.0.2.tgz
npm http 200 https://registry.npmjs.org/mongodb/0.9.6-16
npm http GET https://registry.npmjs.org/mongodb/-/mongodb-0.9.6-16.tgz
npm http 200 https://registry.npmjs.org/express/-/express-2.4.6.tgz
npm http 200 https://registry.npmjs.org/mongodb/-/mongodb-0.9.6-16.tgz
npm WARN mongodb@0.9.6-16 package.json: bugs['web'] should probably be bugs['url']
npm WARN nodeunit@0.5.1 package.json: bugs['web'] should probably be bugs['url']

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: express@2.4.6
npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
npm ERR! Actual:   {"npm":"1.1.0-3","node":"0.6.10"}
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd .../myfavoritebeer.org
npm ERR! node -v v0.6.10
npm ERR! npm -v 1.1.0-3
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm not ok
```

Changing the requested version of express to 2.5.4 (what seems to be the current 2.x branch version) allows "npm install" to complete, however, I am now getting failure when trying to execute "npm start" (Cannot find module 'connect'), which I'm just starting to investigate.

**Comment by MichaelHackett** [comment]
BTW, solved the second problem by adding a line for the connect module ("connect" : "1.8.5") to package.json. As I said, I'm new to npm, but it appears that it is installing only explicitly named modules in the local node_modules directory, and storing dependencies in ~/.npm, but not picking those others up when running the app.

I expect I'm going to run into more problems with missing modules when I start hitting the app. Am I missing some important configuration step(s)?

**Comment by davidascher** [comment]
Yeah, something went weird with the dependencies.

I've tweaked package.json with:
-    "express": "2.4.6",
-    "express": "",
-    "connect": "",

and now npm install works, but npm start puts up a site which, when loaded results in an infininte loop with the following key bits:

TypeError: Not a string or buffer
    at Object.createHmac (crypto.js:129:21)
    at Object.sign (/Users/davida/src/personalike/node_modules/connect/lib/utils.js:135:6)
    at Object.serialize (/Users/davida/src/personalike/node_modules/connect/lib/middleware/session/cookie.js:115:17)
    at ServerResponse.<anonymous> (/Users/davida/src/personalike/node_modules/connect-cookie-session/lib/connect-cookie-session.js:31:56)
    at ServerResponse.writeHead (/Users/davida/src/personalike/node_modules/postprocess/connect-postprocess.js:63:21)
    at ServerResponse._implicitHeader (http.js:805:8)
    at ServerResponse.<anonymous> (http.js:580:10)
    at ServerResponse.end (/Users/davida/src/personalike/node_modules/postprocess/connect-postprocess.js:95:19)
    at next (/Users/davida/src/personalike/node_modules/express/node_modules/connect/lib/http.js:167:13)
    at pass (/Users/davida/src/personalike/node_modules/express/lib/router/index.js:219:24)
TypeError: Not a string or buffer
    at Object.createHmac (crypto.js:129:21)
    at Object.sign (/Users/davida/src/personalike/node_modules/connect/lib/utils.js:135:6)
    at Object.serialize (/Users/davida/src/personalike/node_modules/connect/lib/middleware/session/cookie.js:115:17)
    at ServerResponse.<anonymous> (/Users/davida/src/personalike/node_modules/connect-cookie-session/lib/connect-cookie-session.js:31:56)
    at ServerResponse.writeHead (/Users/davida/src/personalike/node_modules/postprocess/connect-postprocess.js:63:21)
    at ServerResponse._implicitHeader (http.js:805:8)
    at ServerResponse.<anonymous> (http.js:580:10)
    at ServerResponse.end (/Users/davida/src/personalike/node_modules/postprocess/connect-postprocess.js:95:19)
    at next (/Users/davida/src/personalike/node_modules/express/node_modules/connect/lib/http.js:167:13)
    at pass (/Users/davida/src/personalike/node_modules/express/lib/router/index.js:219:24)

**Comment by lloyd** [comment]
on it.
