### ISSUE TITLE
Startup error: Cannot find module 'cookies'

### ISSUE THREAD

**Issue by inactivist** [lloyd/myfavoritebeer.org#51]
I followed the installation instructions in README.md ("Run it!") - but I receive the following error:

```
inactivist@inactivist-VirtualBox:~/src/myfavoritebeer.org$ PORT=8080 npm start

> myfavoritebeer@0.0.1 start /home/inactivist/src/myfavoritebeer.org
> node server/main.js


node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'cookies'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/inactivist/src/myfavoritebeer.org/node_modules/client-sessions/lib/client-sessions.js:2:15)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

npm ERR! myfavoritebeer@0.0.1 start: `node server/main.js`
npm ERR! `sh "-c" "node server/main.js"` failed with 1
npm ERR! 
npm ERR! Failed at the myfavoritebeer@0.0.1 start script.
npm ERR! This is most likely a problem with the myfavoritebeer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls myfavoritebeer
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-13-generic
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /home/inactivist/src/myfavoritebeer.org
npm ERR! node -v v0.6.14
npm ERR! npm -v 1.1.12
npm ERR! code ELIFECYCLE
npm ERR! message myfavoritebeer@0.0.1 start: `node server/main.js`
npm ERR! message `sh "-c" "node server/main.js"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/inactivist/src/myfavoritebeer.org/npm-debug.log
npm not ok
```

Version info:

```
~/src/myfavoritebeer.org$ git branch -v
* master 094eb6a update deployment documentation with 0.6 requirement
~/src/myfavoritebeer.org$ node -v
v0.6.14
~/src/myfavoritebeer.org$ npm -v
1.1.12
~/src/myfavoritebeer.org$ cat /etc/issue
Ubuntu 11.04
```

**Comment by inactivist** [comment]
Workaround: I had to install `cookies` and `node-proxy` using npm (installing `cookies` then re-starting the example resulted in another startup error message that `node-proxy` could not be found.)

My question is: should these dependencies be listed in the `package.json` file, or, did I misread the instructions?

**Comment by inactivist** [comment]
#jbonacci: I'll close it for you.  :D

**Comment by martianmartian** [comment]
I have this problem now..
what was the working solution?
